apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: mockpipelines.devopsconsole.openshift.io
spec:
  group: devopsconsole.openshift.io
  names:
    kind: MockPipeline
    listKind: MockPipelineList
    plural: mockpipelines
    singular: mockpipeline
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          namespace: string
        spec:
          properties:
            app:
              type: "string"
              minimum: 1
            codebase:
              type: "string"
              minimum: 1
            buildtype:
              type: "string"
              minimum: 1 
            listenport:
              type: "number"
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true 